# Generated by Django 5.2.4 on 2025-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и фамилия')),
                ('description', models.TextField(verbose_name='Характеристика')),
                ('type', models.CharField(choices=[('HR', 'сотрудник отдела кадров'), ('candidate', 'кандидат')], default='кандидат', verbose_name='Тип пользователя')),
                ('interview_count_passed', models.IntegerField(default=0, verbose_name='Количество пройденных собеседований на сайте')),
                ('positive_results', models.IntegerField(default=0, verbose_name='Количество положительно пройденных собеседований на сайте')),
                ('negative_results', models.IntegerField(default=0, verbose_name='Количество отрицательно пройденных собеседований на сайте')),
                ('interview_count_taken', models.IntegerField(default=0, verbose_name='Количество проведённых собеседований на сайте')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
