# Generated by Django 5.2.4 on 2025-07-08 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание запроса')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает рассмотрения'), ('accepted', 'Принято'), ('ended successfully', 'закончилось успешно'), ('ended unsuccessfully', 'закончилось безуспешно')], default='waiting', verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кандидат')),
                ('hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_requests', to=settings.AUTH_USER_MODEL, verbose_name='HR менеджер')),
            ],
            options={
                'verbose_name': 'Запрос на собеседование',
                'verbose_name_plural': 'Запросы на собеседование',
                'ordering': ['-created_at'],
            },
        ),
    ]
